#!/usr/bin/env python3
import boto3

dynamodb = boto3.resource('dynamodb')
table = dynamodb.Table('anycompany-rules-prod')

rules = [
    # LO1001 - Identification Rules (9 rules)
    {'rule_id': 'LO1001.03', 'name': 'Agent Name in Massachusetts', 'description': 'Agent did not provide first/last name in Massachusetts', 'category': 'identification', 'severity': 'major', 'active': True, 'logic': {'type': 'pattern_match_conditional', 'condition': {'state': 'MA'}, 'patterns': ['my name is', 'this is', 'speaking'], 'timeFrame': 'first_60_seconds', 'required': True}},
    {'rule_id': 'LO1001.04', 'name': 'Alias Usage', 'description': 'Agent used an Alias in Michigan or New Hampshire or Arizona', 'category': 'identification', 'severity': 'major', 'active': True, 'logic': {'type': 'reference_check', 'condition': {'state': ['MI', 'NH', 'AZ']}, 'check': 'alias_usage', 'required': False}},
    {'rule_id': 'LO1001.05', 'name': 'Untraceable Name', 'description': 'Agent provided a name that cannot be traced back to them and is not on alias log', 'category': 'identification', 'severity': 'moderate', 'active': True, 'logic': {'type': 'reference_validation', 'check': 'agent_name_traceable', 'required': True}},
    {'rule_id': 'LO1001.06', 'name': 'Agent Name Missing', 'description': 'Agent did not state their name', 'category': 'identification', 'severity': 'minor', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['my name is', 'this is', 'speaking'], 'timeFrame': 'first_60_seconds', 'required': True}},
    {'rule_id': 'LO1001.08', 'name': 'Customer Name on Voicemail', 'description': 'Agent did not use the customer\'s first and last name, including suffix, on the voicemail', 'category': 'identification', 'severity': 'minor', 'active': True, 'logic': {'type': 'reference_match', 'check': 'customer_full_name', 'context': 'voicemail', 'required': True}},
    {'rule_id': 'LO1001.09', 'name': 'Incorrect Customer Name', 'description': 'Agent used incorrect customer name on voicemail', 'category': 'identification', 'severity': 'minor', 'active': True, 'logic': {'type': 'reference_validation', 'check': 'customer_name_accuracy', 'context': 'voicemail', 'required': True}},
    {'rule_id': 'LO1001.10', 'name': 'AnyCompany Servicing ID (State-Specific)', 'description': 'Agent did not state "AnyCompany Servicing" when identifying servicer at the beginning of call or when leaving a message (TX, HI, OR, AR, IA, ND, VT, WV)', 'category': 'identification', 'severity': 'moderate', 'active': True, 'logic': {'type': 'pattern_match_conditional', 'condition': {'state': ['TX', 'HI', 'OR', 'AR', 'IA', 'ND', 'VT', 'WV']}, 'patterns': ['anycompany servicing'], 'timeFrame': 'first_60_seconds', 'required': True}},
    {'rule_id': 'LO1001.11', 'name': 'DNC with Good Number', 'description': 'Call made to a number flagged as Do Not Call; however, another phone field reflects as Good and there is no indication the cease and desist has been rescinded', 'category': 'identification', 'severity': 'moderate', 'active': True, 'logic': {'type': 'reference_check', 'check': 'dnc_status', 'required': False}},
    {'rule_id': 'LO1001.12', 'name': 'AnyCompany Servicing ID (General)', 'description': 'Agent did not state "AnyCompany Servicing" when identifying servicer at the beginning of call or when leaving a message', 'category': 'identification', 'severity': 'minor', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['anycompany servicing'], 'timeFrame': 'first_60_seconds', 'required': True}},
    
    # LO1005 - Communication Rules (19 rules)
    {'rule_id': 'LO1005.02', 'name': 'Third Party Disclosure', 'description': 'Disclosed account status or personal information with Third party', 'category': 'communication', 'severity': 'major', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['account balance', 'payment due', 'overdue', 'collections'], 'context': 'third_party_call', 'required': False}},
    {'rule_id': 'LO1005.04', 'name': 'Cease and Desist Call', 'description': 'Called a phone number that is flagged as Cease and Desist or Verbal Do Not Call', 'category': 'communication', 'severity': 'major', 'active': True, 'logic': {'type': 'reference_check', 'check': 'cease_desist_flag', 'required': False}},
    {'rule_id': 'LO1005.05', 'name': 'Attorney Represented Account', 'description': 'Called a customer or engaged in collection activity on an account that is represented by an Attorney', 'category': 'communication', 'severity': 'major', 'active': True, 'logic': {'type': 'reference_check', 'check': 'attorney_retained', 'required': False}},
    {'rule_id': 'LO1005.06', 'name': 'Bankruptcy Protected Account', 'description': 'Called a customer or engaged in collection activity on an account that is protected by bankruptcy', 'category': 'communication', 'severity': 'major', 'active': True, 'logic': {'type': 'reference_check', 'check': 'bankruptcy_filed', 'required': False}},
    {'rule_id': 'LO1005.07', 'name': 'Calling Rules Violation', 'description': 'Did not follow calling rules requirement regarding allowable communications with Customer or Third party and regulations were violated', 'category': 'communication', 'severity': 'major', 'active': True, 'logic': {'type': 'complex_validation', 'check': 'calling_rules_compliance', 'required': True}},
    {'rule_id': 'LO1005.08', 'name': 'SMS Without Consent', 'description': 'Collector sent a SMS Text Message while leaving a voicemail and consent was not granted', 'category': 'communication', 'severity': 'major', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['text message', 'sms', 'texted'], 'check': 'sms_consent', 'required': False}},
    {'rule_id': 'LO1005.09', 'name': 'License Requirement', 'description': 'Agent did not have MN Collections License or agent transferred MN, CT or NV customer to offshore supplier and payment or collection activity occurred', 'category': 'communication', 'severity': 'major', 'active': True, 'logic': {'type': 'reference_check', 'condition': {'state': ['MN', 'CT', 'NV']}, 'check': 'agent_license', 'required': True}},
    {'rule_id': 'LO1005.10', 'name': 'Cease and Desist Flag Removal', 'description': 'Agent removed cease and desist flag', 'category': 'communication', 'severity': 'major', 'active': True, 'logic': {'type': 'system_check', 'check': 'flag_modification', 'required': False}},
    {'rule_id': 'LO1005.11', 'name': 'DNC Call with Good Field', 'description': 'Call made to a number flagged as Do Not Call; however, another phone field reflects as Good and there is no indication the cease and desist has been rescinded', 'category': 'communication', 'severity': 'moderate', 'active': True, 'logic': {'type': 'reference_check', 'check': 'do_not_call', 'required': False}},
    {'rule_id': 'LO1005.12', 'name': 'AnyCompany Calling Rules', 'description': 'Did not follow AnyCompany calling rule requirements regarding allowable communications with Customer or third party', 'category': 'communication', 'severity': 'moderate', 'active': True, 'logic': {'type': 'complex_validation', 'check': 'ally_calling_rules', 'required': True}},
    {'rule_id': 'LO1005.13', 'name': 'Company Name at POE', 'description': 'Agent left company name on message to customer at place of employment or provided company name without being asked first', 'category': 'communication', 'severity': 'moderate', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['anycompany', 'anycompany servicing'], 'context': 'place_of_employment', 'required': False}},
    {'rule_id': 'LO1005.14', 'name': 'Inappropriate Voicemail', 'description': 'Inappropriate content left on voicemail - Profanity', 'category': 'communication', 'severity': 'moderate', 'active': True, 'logic': {'type': 'sentiment_analysis', 'check': 'profanity_detection', 'context': 'voicemail', 'required': False}},
    {'rule_id': 'LO1005.15', 'name': 'Disconnected Number Call', 'description': 'Manual call placed to phone number that was identified as disconnected and reassigned or a wrong number', 'category': 'communication', 'severity': 'moderate', 'active': True, 'logic': {'type': 'reference_check', 'check': 'phone_status', 'required': False}},
    {'rule_id': 'LO1005.16', 'name': 'Personal Email Usage', 'description': 'Agent provided email address or communicated with customer using AnyCompany personal email address', 'category': 'communication', 'severity': 'moderate', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['@anycompany.com', 'email', 'send you an email'], 'check': 'personal_email_usage', 'required': False}},
    {'rule_id': 'LO1005.18', 'name': 'Medical Info Documentation', 'description': 'Specific medical condition or personal identifying information was documented in the system', 'category': 'communication', 'severity': 'moderate', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['medical', 'hospital', 'doctor', 'surgery', 'illness'], 'check': 'medical_info_documentation', 'required': False}},
    {'rule_id': 'LO1005.19', 'name': 'Creditor Name to Third Party', 'description': 'Creditor name disclosed to Third party without being asked', 'category': 'communication', 'severity': 'minor', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['anycompany', 'anycompany servicing'], 'context': 'third_party_call', 'required': False}},
    {'rule_id': 'LO1005.24', 'name': 'Debt Perception to Third Party', 'description': 'Collector provided information to Third party that could be perceived as customer owes a debt or is in collections', 'category': 'communication', 'severity': 'minor', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['payment', 'debt', 'owe', 'collections'], 'context': 'third_party_call', 'required': False}},
    {'rule_id': 'LO1005.25', 'name': 'PII Disclosure', 'description': 'Disclosed personal or contact information with OKTTT, Customer or Co-buyer - Any PII', 'category': 'communication', 'severity': 'minor', 'active': True, 'logic': {'type': 'pii_detection', 'check': 'pii_disclosure', 'required': False}},
    {'rule_id': 'LO1005.26', 'name': 'Partial PII to Third Party', 'description': 'Disclosed partial personal information with Third party - Any PII', 'category': 'communication', 'severity': 'minor', 'active': True, 'logic': {'type': 'pii_detection', 'check': 'partial_pii_disclosure', 'context': 'third_party_call', 'required': False}},
    {'rule_id': 'LO1005.27', 'name': 'SMS Policy Violation', 'description': 'Collector sent a SMS Text Message while leaving a voicemail. Consent granted however outside of AnyCompany policy', 'category': 'communication', 'severity': 'minor', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['text message', 'sms'], 'check': 'sms_policy_compliance', 'required': False}},
    
    # LO1006 - Policy Rules (10 rules)
    {'rule_id': 'LO1006.02', 'name': 'Medical Info to Third Party', 'description': 'Specific medical information disclosed to a Third party - Medical information', 'category': 'policy', 'severity': 'major', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['medical', 'hospital', 'doctor', 'surgery', 'illness', 'medication'], 'context': 'third_party_call', 'required': False}},
    {'rule_id': 'LO1006.03', 'name': 'Pre-Cure Payment Demand', 'description': 'Payments demanded prior to the expiration of the cure period', 'category': 'policy', 'severity': 'major', 'active': True, 'logic': {'type': 'reference_check_conditional', 'condition': {'cure_period_expired': False}, 'patterns': ['pay now', 'payment due', 'must pay'], 'required': False}},
    {'rule_id': 'LO1006.04', 'name': 'Pre-Cure Repo Threat', 'description': 'Agent stated or threatened repossession or legal action will occur prior to the end of the cure period', 'category': 'policy', 'severity': 'major', 'active': True, 'logic': {'type': 'reference_check_conditional', 'condition': {'cure_period_expired': False}, 'patterns': ['repossess', 'take your car', 'legal action'], 'required': False}},
    {'rule_id': 'LO1006.18', 'name': 'Activity Code Impact', 'description': 'Incorrect Activity Code that impacted Calling Rules and is a potential negative impact to customer', 'category': 'policy', 'severity': 'minor', 'active': True, 'logic': {'type': 'system_check', 'check': 'activity_code_accuracy', 'required': True}},
    {'rule_id': 'LO1006.20', 'name': 'Non-Specific Medical to Third Party', 'description': 'Disclosed non-specific medical information to third party', 'category': 'policy', 'severity': 'moderate', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['health', 'medical issue', 'not feeling well'], 'context': 'third_party_call', 'required': False}},
    {'rule_id': 'LO1006.35', 'name': 'Medical Info Documentation', 'description': 'Documented non-specific medical information in the system of record', 'category': 'policy', 'severity': 'minor', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['health', 'medical', 'sick'], 'check': 'system_documentation', 'required': False}},
    {'rule_id': 'LO1007.05', 'name': 'Threats of Imprisonment', 'description': 'Agents made threats such as garnishment or imprisonment', 'category': 'policy', 'severity': 'major', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['jail', 'prison', 'arrest', 'garnish', 'sue you'], 'required': False}},
    {'rule_id': 'LO1007.06', 'name': 'False Action Threats', 'description': 'Agent threatened repossession or legal action when such action will not be taken', 'category': 'policy', 'severity': 'major', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['destroy your credit', 'ruin your credit forever'], 'check': 'false_threat_validation', 'required': False}},
    {'rule_id': 'LO1007.07', 'name': 'Fraudulent Representations', 'description': 'Agent made fraudulent, misleading, or deceptive representations', 'category': 'policy', 'severity': 'major', 'active': True, 'logic': {'type': 'sentiment_analysis', 'check': 'fraudulent_representation', 'required': False}},
    {'rule_id': 'LO1007.16', 'name': 'False Manager Identity', 'description': 'Identified themselves as a manager of the account', 'category': 'policy', 'severity': 'minor', 'active': True, 'logic': {'type': 'pattern_match', 'patterns': ['i am the manager', 'manager of your account'], 'check': 'manager_identity_validation', 'required': False}},
    
    # LO1009 - System Rules (4 rules)
    {'rule_id': 'LO1009.03', 'name': 'Missing Contact Documentation', 'description': 'Contact was not documented in system', 'category': 'system', 'severity': 'major', 'active': True, 'logic': {'type': 'system_check', 'check': 'contact_documentation', 'required': True}},
    {'rule_id': 'LO1009.05', 'name': 'Activity Code Customer Impact', 'description': 'Incorrect Activity Code that impacted Calling Rules and was a negative impact to customer', 'category': 'system', 'severity': 'moderate', 'active': True, 'logic': {'type': 'system_check', 'check': 'activity_code_customer_impact', 'required': True}},
    {'rule_id': 'LO1009.08', 'name': 'Activity Code AnyCompany Impact', 'description': 'Incorrect Activity Code that impacted Calling Rules and was a negative impact to AnyCompany', 'category': 'system', 'severity': 'minor', 'active': True, 'logic': {'type': 'system_check', 'check': 'activity_code_ally_impact', 'required': True}},
    {'rule_id': 'LO1009.09', 'name': 'Activity Code Potential Impact', 'description': 'Incorrect Activity Code that impacted Calling Rules and is a potential negative impact to customer', 'category': 'system', 'severity': 'minor', 'active': True, 'logic': {'type': 'system_check', 'check': 'activity_code_potential_impact', 'required': True}}
]

for rule in rules:
    try:
        table.put_item(Item=rule)
        print(f"✅ Added rule {rule['rule_id']}")
    except:
        print(f"⚠️ Rule {rule['rule_id']} exists")

print(f"✅ {len(rules)} compliance rules with comprehensive logic populated")